spring:
  application:
    name: 'GraphQl-API'
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  # to enable graphql dashbord simailr to swagger
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  # Force Spring Boot to always run initialization
#  sql:
#    init:
#      mode: always
#      # Point to your custom script locations
#      schema-locations: classpath:db-scripts/schema.sql
#      data-locations: classpath:db-scripts/data.sql
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'


